version: '3'
services:
  webjail:
    container_name: webjail
    hostname: webjail
    image: webjail
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - FLAG=SparkCTF{p4l1Ndr0m3s_g0_brrr}
    ports:
      - 2500:2500
  nginx:
    container_name: webjail_nginx
    image: nginx:latest
    ports:
      - "2501:2501"
    expose: 
      - 2501
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webjail